name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy dependency folder
        run: |
          mkdir -p deps
          echo "dependency file" > deps/file.txt

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: deps
          key: cache-d09f9b9

      - name: prime-cache-d09f9b9
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"