name: Combined CI

on:
  push:
    branches:
      - main

jobs:
  combined-job:
    runs-on: ubuntu-latest

    steps:
      - name: 24f1002360@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Prepare dependencies
        run: |
          mkdir -p deps
          echo "dummy file" > deps/file.txt

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: deps
          key: cache-d09f9b9

      - name: prime-cache-d09f9b9
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"